### ISSUE TITLE
Concern about open-source project advertising paid component

### ISSUE THREAD

**Issue by JCKodel** [glowbom/glowby#1]
One more company that "opens source" something only with the purpose of advertising its paid component.

**Comment by jacob-i** [comment]
Hi @JCKodel,

I've updated the issue title to better reflect your concern, as we value respectful dialogue in our community.

To address your concern: All features of Glowby Basic, including interactions with LLMs and AI-related APIs, are entirely free and open-source. We do not offer premium features within this project. 

Your feedback is appreciated. If you have further questions or suggestions, feel free to share.

Best,
Jacob

**Comment by jacob-i** [comment]
Closing this now, but further feedback is always welcome.
